### ISSUE TITLE
Hover text is not escaped

### ISSUE THREAD

**Issue by kylereedmsft** [microsoft/vscode-lsif-extension#20]
C++ template hover text will have characters `<` and `>` in the hover text.
e.g. `vector<int> v` which rendered in VS Code as `vector v`.

The hover text needs to be properly escaped or its content type set before it is returned.

**Comment by dbaeumer** [comment]
@kylereedmsft that is strange since this is correctly rendered for TS. See 
<img width="328" alt="capture" src="https://user-images.githubusercontent.com/1931590/107744334-cb257280-6d12-11eb-83e8-a6e60305809d.png">

How do you generate the hover. If you want to have code in there you need to generate a markdown hover with fenced code blocks.

**Comment by kylereedmsft** [comment]
The hover text is just a plain string like this:
{"id":11,"type":"vertex","label":"hoverResult","result":{"contents":"template<class T> void f()"}}


It looks like the TS example is specifying the language there. Should that fix the rendering?

**Comment by kylereedmsft** [comment]
Changing the hover result to this works as expected:

{"id":11,"type":"vertex","label":"hoverResult","result":{"contents":[{"language":"cpp","value":"struct List<T>"}]}}

Note the difference. In the first case, the content is just a string and so needs escaping. In the working example, the contents is structured content and works as expected.
